[2023-02-08T19:28:45.856+0000] {processor.py:153} INFO - Started process (PID=66) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:28:45.858+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:28:45.859+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:28:45.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:28:49.518+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:28:49.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:28:49.520+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:28:49.554+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 3.704 seconds
[2023-02-08T19:29:20.215+0000] {processor.py:153} INFO - Started process (PID=145) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:29:20.217+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:29:20.218+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:29:20.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:29:20.580+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:29:20.579+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:29:20.581+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:29:20.614+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.404 seconds
[2023-02-08T19:29:50.773+0000] {processor.py:153} INFO - Started process (PID=221) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:29:50.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:29:50.775+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:29:50.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:29:51.071+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:29:51.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:29:51.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:29:51.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.331 seconds
[2023-02-08T19:30:21.526+0000] {processor.py:153} INFO - Started process (PID=286) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:30:21.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:30:21.528+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:30:21.528+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:30:21.828+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:30:21.827+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:30:21.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:30:21.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.339 seconds
[2023-02-08T19:30:52.122+0000] {processor.py:153} INFO - Started process (PID=352) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:30:52.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:30:52.124+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:30:52.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:30:52.501+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:30:52.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:30:52.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:30:52.538+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.422 seconds
[2023-02-08T19:31:22.588+0000] {processor.py:153} INFO - Started process (PID=431) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:31:22.589+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:31:22.590+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:31:22.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:31:22.868+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:31:22.867+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:31:22.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:31:22.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.315 seconds
[2023-02-08T19:31:52.993+0000] {processor.py:153} INFO - Started process (PID=495) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:31:52.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:31:52.996+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:31:52.996+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:31:53.291+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:31:53.290+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:31:53.291+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:31:53.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.329 seconds
[2023-02-08T19:32:23.439+0000] {processor.py:153} INFO - Started process (PID=573) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:32:23.441+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:32:23.442+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:32:23.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:32:23.831+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:32:23.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:32:23.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:32:23.874+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.440 seconds
[2023-02-08T19:32:53.953+0000] {processor.py:153} INFO - Started process (PID=640) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:32:53.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:32:53.955+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:32:53.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:32:54.226+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:32:54.224+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:32:54.226+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:32:54.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.304 seconds
[2023-02-08T19:33:24.408+0000] {processor.py:153} INFO - Started process (PID=708) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:33:24.409+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:33:24.410+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:33:24.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:33:24.676+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:33:24.675+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:33:24.676+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:33:24.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.304 seconds
[2023-02-08T19:33:55.446+0000] {processor.py:153} INFO - Started process (PID=785) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:33:55.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:33:55.449+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:33:55.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:33:55.888+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:33:55.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:33:55.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:33:55.928+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.488 seconds
[2023-02-08T19:34:26.042+0000] {processor.py:153} INFO - Started process (PID=846) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:34:26.044+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:34:26.045+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:34:26.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:34:26.352+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:34:26.351+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:34:26.352+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:34:26.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.361 seconds
[2023-02-08T19:34:57.264+0000] {processor.py:153} INFO - Started process (PID=912) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:34:57.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:34:57.266+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:34:57.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:34:57.665+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:34:57.664+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:34:57.666+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:34:57.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.441 seconds
[2023-02-08T19:35:28.195+0000] {processor.py:153} INFO - Started process (PID=988) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:35:28.196+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:35:28.197+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:35:28.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:35:28.480+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:35:28.479+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:35:28.481+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:35:28.509+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.318 seconds
[2023-02-08T19:35:58.627+0000] {processor.py:153} INFO - Started process (PID=1053) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:35:58.628+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:35:58.629+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:35:58.629+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:35:58.902+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:35:58.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:35:58.903+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:35:58.933+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.310 seconds
[2023-02-08T19:36:29.003+0000] {processor.py:153} INFO - Started process (PID=1127) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:36:29.004+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:36:29.005+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:36:29.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:36:29.570+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:36:29.569+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:36:29.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:36:29.615+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.618 seconds
[2023-02-08T19:36:59.710+0000] {processor.py:153} INFO - Started process (PID=1196) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:36:59.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:36:59.713+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:36:59.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:37:00.015+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:37:00.014+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:37:00.016+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:37:00.049+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.345 seconds
[2023-02-08T19:37:30.113+0000] {processor.py:153} INFO - Started process (PID=1261) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:37:30.115+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:37:30.116+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:37:30.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:37:30.439+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:37:30.438+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:37:30.440+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:37:30.468+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.361 seconds
[2023-02-08T19:38:01.165+0000] {processor.py:153} INFO - Started process (PID=1339) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:38:01.167+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:38:01.168+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:38:01.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:38:01.451+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:38:01.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:38:01.452+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:38:01.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.321 seconds
[2023-02-08T19:38:31.618+0000] {processor.py:153} INFO - Started process (PID=1404) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:38:31.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:38:31.620+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:38:31.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:38:31.907+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:38:31.906+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:38:31.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:38:31.939+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.325 seconds
[2023-02-08T19:39:02.033+0000] {processor.py:153} INFO - Started process (PID=1483) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:39:02.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:39:02.038+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:39:02.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:39:02.428+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:39:02.426+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:39:02.428+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:39:02.461+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.444 seconds
[2023-02-08T19:39:32.729+0000] {processor.py:153} INFO - Started process (PID=1548) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:39:32.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:39:32.731+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:39:32.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:39:33.026+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:39:33.025+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:39:33.026+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:39:33.057+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.332 seconds
[2023-02-08T19:40:03.227+0000] {processor.py:153} INFO - Started process (PID=1615) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:40:03.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:40:03.229+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:40:03.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:40:03.562+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:40:03.560+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:40:03.562+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:40:03.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.383 seconds
[2023-02-08T19:40:33.774+0000] {processor.py:153} INFO - Started process (PID=1692) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:40:33.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:40:33.775+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:40:33.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:40:34.038+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:40:34.036+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:40:34.038+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:40:34.071+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.301 seconds
[2023-02-08T19:41:04.109+0000] {processor.py:153} INFO - Started process (PID=1756) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:41:04.110+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:41:04.111+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:41:04.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:41:04.360+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:41:04.359+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:41:04.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:41:04.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.289 seconds
[2023-02-08T19:41:34.452+0000] {processor.py:153} INFO - Started process (PID=1828) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:41:34.460+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:41:34.461+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:41:34.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:41:34.939+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:41:34.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:41:34.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:41:34.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.534 seconds
[2023-02-08T19:42:05.090+0000] {processor.py:153} INFO - Started process (PID=1898) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:42:05.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:42:05.093+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:42:05.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:42:05.343+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:42:05.342+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:42:05.344+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:42:05.371+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.286 seconds
[2023-02-08T19:42:35.445+0000] {processor.py:153} INFO - Started process (PID=1964) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:42:35.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:42:35.447+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:42:35.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:42:35.807+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:42:35.806+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:42:35.808+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:42:35.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.429 seconds
[2023-02-08T19:43:05.998+0000] {processor.py:153} INFO - Started process (PID=2041) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:43:06.009+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:43:06.010+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:43:06.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:43:06.285+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:43:06.283+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:43:06.285+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:43:06.314+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.323 seconds
[2023-02-08T19:43:36.365+0000] {processor.py:153} INFO - Started process (PID=2110) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:43:36.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:43:36.367+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:43:36.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:43:36.630+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:43:36.628+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:43:36.630+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:43:36.658+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.297 seconds
[2023-02-08T19:44:06.864+0000] {processor.py:153} INFO - Started process (PID=2184) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:44:06.865+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:44:06.867+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:44:06.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:44:07.329+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:44:07.327+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:44:07.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:44:07.388+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.533 seconds
[2023-02-08T19:44:37.569+0000] {processor.py:153} INFO - Started process (PID=2251) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:44:37.570+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:44:37.571+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:44:37.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:44:37.839+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:44:37.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:44:37.839+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:44:37.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.303 seconds
[2023-02-08T19:45:08.052+0000] {processor.py:153} INFO - Started process (PID=2316) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:45:08.054+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:45:08.056+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:45:08.055+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:45:08.313+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:45:08.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:45:08.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:45:08.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.295 seconds
[2023-02-08T19:45:39.012+0000] {processor.py:153} INFO - Started process (PID=2394) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:45:39.013+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:45:39.014+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:45:39.014+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:45:39.304+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:45:39.303+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:45:39.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:45:39.332+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.324 seconds
[2023-02-08T19:46:09.505+0000] {processor.py:153} INFO - Started process (PID=2460) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:46:09.506+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:46:09.507+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:46:09.507+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:46:09.806+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:46:09.805+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:46:09.807+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:46:09.835+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.336 seconds
[2023-02-08T19:46:39.932+0000] {processor.py:153} INFO - Started process (PID=2536) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:46:39.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:46:39.935+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:46:39.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:46:40.360+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:46:40.359+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:46:40.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:46:40.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.482 seconds
[2023-02-08T19:47:10.539+0000] {processor.py:153} INFO - Started process (PID=2601) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:47:10.540+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:47:10.541+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:47:10.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:47:10.803+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:47:10.802+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:47:10.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:47:10.830+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.295 seconds
[2023-02-08T19:47:40.860+0000] {processor.py:153} INFO - Started process (PID=2667) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:47:40.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:47:40.862+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:47:40.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:47:41.148+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:47:41.146+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:47:41.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:47:41.178+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.322 seconds
[2023-02-08T19:48:11.481+0000] {processor.py:153} INFO - Started process (PID=2744) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:48:11.482+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:48:11.483+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:48:11.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:48:11.792+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:48:11.791+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:48:11.792+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:48:11.822+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.347 seconds
[2023-02-08T19:48:41.863+0000] {processor.py:153} INFO - Started process (PID=2809) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:48:41.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:48:41.865+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:48:41.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:48:42.148+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:48:42.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:48:42.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:48:42.178+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.319 seconds
[2023-02-08T19:49:12.464+0000] {processor.py:153} INFO - Started process (PID=2875) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:49:12.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:49:12.466+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:49:12.466+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:49:13.046+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:49:13.045+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:49:13.047+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:49:13.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.643 seconds
[2023-02-08T19:49:43.880+0000] {processor.py:153} INFO - Started process (PID=2953) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:49:43.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:49:43.882+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:49:43.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:49:44.134+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:49:44.133+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:49:44.134+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:49:44.166+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.290 seconds
[2023-02-08T19:50:14.222+0000] {processor.py:153} INFO - Started process (PID=3019) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:50:14.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:50:14.224+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:50:14.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:50:14.570+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:50:14.569+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:50:14.570+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:50:14.604+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.389 seconds
[2023-02-08T19:50:44.681+0000] {processor.py:153} INFO - Started process (PID=3095) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:50:44.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:50:44.682+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:50:44.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:50:45.044+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:50:45.042+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:50:45.044+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:50:45.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.424 seconds
[2023-02-08T19:51:15.278+0000] {processor.py:153} INFO - Started process (PID=3160) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:51:15.279+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:51:15.280+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:51:15.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:51:15.584+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:51:15.582+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:51:15.584+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:51:15.623+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.350 seconds
[2023-02-08T19:51:46.010+0000] {processor.py:153} INFO - Started process (PID=3236) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:51:46.012+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:51:46.014+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:51:46.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:51:46.509+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:51:46.507+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:51:46.510+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:51:46.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.608 seconds
[2023-02-08T19:52:16.812+0000] {processor.py:153} INFO - Started process (PID=3304) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:52:16.813+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:52:16.814+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:52:16.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:52:17.113+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:52:17.112+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:52:17.113+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:52:17.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.339 seconds
[2023-02-08T19:52:47.566+0000] {processor.py:153} INFO - Started process (PID=3371) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:52:47.572+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:52:47.573+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:52:47.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:52:47.929+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:52:47.927+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:52:47.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:52:47.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.411 seconds
[2023-02-08T19:53:18.044+0000] {processor.py:153} INFO - Started process (PID=3449) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:53:18.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:53:18.047+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:53:18.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:53:18.336+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:53:18.335+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:53:18.337+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:53:18.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.324 seconds
[2023-02-08T19:53:49.107+0000] {processor.py:153} INFO - Started process (PID=3513) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:53:49.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:53:49.109+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:53:49.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:53:49.384+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:53:49.383+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:53:49.384+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:53:49.415+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.313 seconds
[2023-02-08T19:54:20.196+0000] {processor.py:153} INFO - Started process (PID=3591) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:54:20.203+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:54:20.204+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:54:20.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:54:20.722+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:54:20.721+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:54:20.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:54:20.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.599 seconds
[2023-02-08T19:54:51.555+0000] {processor.py:153} INFO - Started process (PID=3657) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:54:51.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:54:51.556+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:54:51.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:54:51.930+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:54:51.929+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:54:51.930+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:54:51.958+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.408 seconds
[2023-02-08T19:55:21.997+0000] {processor.py:153} INFO - Started process (PID=3722) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:55:21.999+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:55:22.000+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:55:21.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:55:22.354+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:55:22.353+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:55:22.355+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:55:22.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.389 seconds
[2023-02-08T19:55:52.844+0000] {processor.py:153} INFO - Started process (PID=3798) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:55:52.845+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:55:52.846+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:55:52.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:55:53.142+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:55:53.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:55:53.142+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:55:53.177+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.337 seconds
[2023-02-08T19:56:23.928+0000] {processor.py:153} INFO - Started process (PID=3863) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:56:23.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:56:23.930+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:56:23.929+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:56:24.211+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:56:24.209+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:56:24.211+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:56:24.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.326 seconds
[2023-02-08T19:56:54.389+0000] {processor.py:153} INFO - Started process (PID=3941) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:56:54.396+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:56:54.399+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:56:54.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:56:54.782+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:56:54.780+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:56:54.782+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:56:54.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.438 seconds
[2023-02-08T19:57:25.258+0000] {processor.py:153} INFO - Started process (PID=4006) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:57:25.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:57:25.260+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:57:25.260+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:57:25.537+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:57:25.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:57:25.538+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:57:25.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.311 seconds
[2023-02-08T19:57:55.817+0000] {processor.py:153} INFO - Started process (PID=4071) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:57:55.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:57:55.820+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:57:55.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:57:56.259+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:57:56.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:57:56.259+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:57:56.293+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.482 seconds
[2023-02-08T19:58:26.527+0000] {processor.py:153} INFO - Started process (PID=4149) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:58:26.528+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:58:26.529+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:58:26.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:58:26.794+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:58:26.793+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:58:26.794+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:58:26.828+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.305 seconds
[2023-02-08T19:58:56.973+0000] {processor.py:153} INFO - Started process (PID=4215) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:58:56.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:58:56.975+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:58:56.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:58:57.295+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:58:57.294+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:58:57.295+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:58:57.326+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.359 seconds
[2023-02-08T19:59:27.608+0000] {processor.py:153} INFO - Started process (PID=4292) to work on /opt/airflow/dags/etlcommands.py
[2023-02-08T19:59:27.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etlcommands.py for tasks to queue
[2023-02-08T19:59:27.611+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:59:27.610+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:59:27.950+0000] {logging_mixin.py:137} INFO - [2023-02-08T19:59:27.949+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etlcommands.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etlcommands.py", line 46, in <module>
    capture_account_data >> is_valid >> [valid, nvalid]
NameError: name 'nvalid' is not defined
[2023-02-08T19:59:27.950+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etlcommands.py
[2023-02-08T19:59:27.981+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etlcommands.py took 0.378 seconds
